### ISSUE TITLE
Typography

### ISSUE THREAD

**Issue by davodey** [davodey/pearson-glp-pl#1]
Add typography from elements - https://pearson-elements-v1.surge.sh/elements/typography/

Also include any missing typography from the UI Kit:

<img width="868" alt="screen shot 2017-07-14 at 10 28 11 am" src="https://user-images.githubusercontent.com/5407196/28223162-2d7fce90-687f-11e7-8f9a-b115af9ed8a6.png">

**Comment by jackiejakob** [comment]
@davodey Should I separate the UI kit and Framework typography into the two folders you created?

**Comment by davodey** [comment]
No remove Framework, and only use UI Kit.

**Comment by davodey** [comment]
@jackiejakob  closing this too.
