### ISSUE TITLE
Pagination hover states

### ISSUE THREAD

**Issue by davodey** [davodey/pearson-glp-pl#39]
When a user hovers over a number in the pagination widget an underline appears.  We're currently achieving this by using text-decoration: underline.  The problem is it's not as visually striking as suggested in the redline.  

Refactor the code so it's more like the redline.

<img width="463" alt="screen shot 2017-07-27 at 8 34 22 pm" src="https://user-images.githubusercontent.com/5407196/28701421-076a00f4-730b-11e7-8adc-2a9bb8deae88.png">

**Comment by davodey** [comment]
wont fix

**Comment by StommePoes** [comment]
Did a 2px solid border-bottom work better?

**Comment by davodey** [comment]
We decided not to do this.  The 2px solid border would LOOK better, but it's a lot more code and complex than what it's worth for prototyping purposes.  The element would have nested divs and spans and chunk up what should be a regular button.  

We can achieve almost the same thing, with a 1px with text-decoration: underline on one element.

**Comment by StommePoes** [comment]
Sensible!
