### ISSUE TITLE
Footer

### ISSUE THREAD

**Issue by davodey** [davodey/pearson-glp-pl#52]
Build out footer 

![screen shot 2017-08-02 at 3 55 34 pm](https://user-images.githubusercontent.com/5407196/28898493-109b97c0-779b-11e7-8a4c-9020b944695c.png)

**Comment by jackiejakob** [comment]
Is there any info on what to do for large and middle breakpoint? The two sides start to crash together before 768px screens.

**Comment by davodey** [comment]
How about creating a custom breakpoint before the crash?  I never follow the UXF recommendations on breakpoints or grids ;)

**Comment by jackiejakob** [comment]
Haha, okay sounds good :)
